# Generated by Django 3.2.13 on 2022-11-27 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.hotel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
