# Generated by Django 3.2.13 on 2022-11-28 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_hotel_moto'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='tag',
            field=models.CharField(default='Bangladesh,3 star', max_length=120),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('room_number', 'hotel')},
        ),
    ]
