# Generated by Django 3.2.13 on 2022-12-13 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20221130_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombook',
            name='stripe_checkout_url',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='roombook',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
