# Generated by Django 3.2.13 on 2022-12-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20221213_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='per_night_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='roombook',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
